import { anthropicProvider } from "./anthropic.js";
import type { BookingAgentBackend } from "./backend.js";
import { checkChatLimit, type ChatLimitOptions } from "./chatLimit.js";
import type { ConversationStore } from "./conversationStore.js";
import { runIntentMatch, type IntentRouter } from "./intentRouter.js";
import type { LlmMessage, LlmProvider } from "./llm.js";
import { openAiProvider } from "./openai.js";
import { buildBookingAgentTools } from "./openaiTools.js";
import { buildBookingAgentSystemPrompt } from "./prompt.js";
import {
  runSecurityChecks,
  type SecurityErrorCode,
  type SecurityOptions,
} from "./security.js";
import { maybeSummarizeHistory, type SummarizeOptions } from "./summarize.js";
import { executeBookingAgentTool } from "./tools.js";

export type BookingAgentUserMessage = {
  role: "user" | "assistant";
  content: string;
};

export type BookingAgentTurnResult =
  | {
      ok: true;
      reply: string;
      /**
       * True when the reply was generated by the chat-limit fallback
       * (the user hit the per-session message cap). The caller can use
       * this to disable the input or surface a banner.
       */
      limited?: boolean;
    }
  | {
      ok: false;
      code:
        | "MISSING_API_KEY"
        | "MISSING_OPENAI_KEY" // legacy alias kept for back-compat
        | "PROVIDER_ERROR"
        | "OPENAI_ERROR" // legacy alias kept for back-compat
        | "OPENAI_EMPTY"
        | "TOOL_LIMIT"
        | SecurityErrorCode;
      error: string;
      hint?: string;
      retryAfterMs?: number;
    };

function sanitizeIncoming(messages: BookingAgentUserMessage[]): BookingAgentUserMessage[] {
  const max = 30;
  const slice = messages.slice(-max);
  return slice.map((m) => ({
    role: m.role,
    content:
      typeof m.content === "string"
        ? m.content.slice(0, 12000)
        : String(m.content ?? "").slice(0, 12000),
  }));
}

/** Built-in providers selectable by name. */
const BUILTIN_PROVIDERS: Record<string, LlmProvider> = {
  openai: openAiProvider,
  anthropic: anthropicProvider,
};

function resolveProvider(
  spec: LlmProvider | "openai" | "anthropic" | undefined,
): LlmProvider {
  if (!spec) return openAiProvider;
  if (typeof spec === "string") {
    const found = BUILTIN_PROVIDERS[spec];
    if (!found) throw new Error(`Unknown provider: ${spec}`);
    return found;
  }
  return spec;
}

function pickApiKey(
  provider: LlmProvider,
  options: {
    apiKey?: string;
    openAiApiKey?: string;
    anthropicApiKey?: string;
  },
): string | undefined {
  if (options.apiKey?.trim()) return options.apiKey;
  if (provider.name === "openai" && options.openAiApiKey?.trim())
    return options.openAiApiKey;
  if (provider.name === "anthropic" && options.anthropicApiKey?.trim())
    return options.anthropicApiKey;
  return undefined;
}

export async function runBookingAgentTurn(options: {
  messages: BookingAgentUserMessage[];
  context?: Record<string, unknown>;
  backend: BookingAgentBackend;
  accountTypeId: string;
  /**
   * LLM provider. Built-in: `"openai"` (default) or `"anthropic"`. You
   * can also pass any object implementing `LlmProvider` to use a
   * custom provider (e.g. local model, Gemini, Mistral).
   */
  provider?: LlmProvider | "openai" | "anthropic";
  /** Generic API key (preferred for custom providers). */
  apiKey?: string;
  /** OpenAI API key (used when provider is "openai" and `apiKey` not set). */
  openAiApiKey?: string;
  /** Anthropic API key (used when provider is "anthropic" and `apiKey` not set). */
  anthropicApiKey?: string;
  /** Override provider's default model. */
  model?: string;
  maxToolSteps?: number;
  store?: ConversationStore;
  sessionId?: string;
  intentRouter?: IntentRouter;
  summarize?: SummarizeOptions;
  allowOutOfScope?: boolean;
  outOfScopeFallbackText?: string;
  security?: SecurityOptions;
  sdkApiKey?: string;
  rateLimitKey?: string;
  chatLimit?: ChatLimitOptions;
}): Promise<BookingAgentTurnResult> {
  if (options.security) {
    const securityResult = await runSecurityChecks({
      messages: options.messages,
      options: options.security,
      providedApiKey: options.sdkApiKey,
      rateLimitKey: options.rateLimitKey ?? options.sessionId,
    });
    if (!securityResult.ok) {
      return {
        ok: false,
        code: securityResult.code,
        error: securityResult.reason,
        retryAfterMs: securityResult.retryAfterMs,
      };
    }
    options = { ...options, messages: securityResult.sanitizedMessages };
  }

  const provider = resolveProvider(options.provider);
  const apiKey = pickApiKey(provider, options);
  if (!apiKey?.trim()) {
    const code: "MISSING_OPENAI_KEY" | "MISSING_API_KEY" =
      provider.name === "openai" ? "MISSING_OPENAI_KEY" : "MISSING_API_KEY";
    return {
      ok: false,
      code,
      error: `${provider.name.toUpperCase()} API key is not configured on the server.`,
      hint:
        provider.name === "openai"
          ? "Set openAiApiKey (or apiKey)."
          : provider.name === "anthropic"
            ? "Set anthropicApiKey (or apiKey)."
            : "Set apiKey.",
    };
  }

  const incoming = sanitizeIncoming(options.messages);
  if (incoming.length === 0) {
    return {
      ok: false,
      code: "PROVIDER_ERROR",
      error: "No messages provided.",
    };
  }

  const useStore = Boolean(options.store && options.sessionId);
  const sessionId = options.sessionId ?? "";
  const priorHistory: BookingAgentUserMessage[] = useStore
    ? sanitizeIncoming(await options.store!.load(sessionId))
    : [];

  const persistTurn = async (reply: string): Promise<void> => {
    if (!useStore) return;
    try {
      await options.store!.append(sessionId, [
        ...incoming,
        { role: "assistant", content: reply },
      ]);
      if (options.summarize) {
        await maybeSummarizeHistory({
          store: options.store!,
          sessionId,
          options: options.summarize,
        });
      }
    } catch {
      // Storage failures must not break the turn; the reply is still valid.
    }
  };

  const chatLimitHit = checkChatLimit({
    priorHistory,
    incoming,
    options: options.chatLimit,
  });
  if (chatLimitHit) {
    await persistTurn(chatLimitHit.reply);
    return { ok: true, reply: chatLimitHit.reply, limited: true };
  }

  if (options.intentRouter) {
    const lastUser = [...incoming].reverse().find((m) => m.role === "user");
    if (lastUser) {
      try {
        const match = await options.intentRouter(lastUser.content, {
          accountTypeId: options.accountTypeId,
          pageContext: options.context,
        });
        if (match) {
          const reply = await runIntentMatch(match, options.backend);
          await persistTurn(reply);
          return { ok: true, reply };
        }
      } catch {
        // Router errors fall through to the LLM; never fail the turn.
      }
    }
  }

  const model = options.model ?? provider.defaultModel;
  const maxSteps = options.maxToolSteps ?? 8;
  const allowOutOfScope = options.allowOutOfScope === true;
  const includeWebSearch =
    allowOutOfScope && typeof options.backend.webSearch === "function";
  const tools = buildBookingAgentTools({ includeWebSearch });

  const system = buildBookingAgentSystemPrompt(
    options.accountTypeId,
    options.context,
    {
      allowOutOfScope,
      outOfScopeFallbackText: options.outOfScopeFallbackText,
    },
  );

  const fullHistory: BookingAgentUserMessage[] = sanitizeIncoming([
    ...priorHistory,
    ...incoming,
  ]);

  const llmMessages: LlmMessage[] = fullHistory.map((m) =>
    m.role === "user"
      ? { role: "user", content: m.content }
      : { role: "assistant", content: m.content },
  );

  for (let step = 0; step < maxSteps; step++) {
    const completion = await provider.request({
      apiKey,
      model,
      system,
      messages: llmMessages,
      tools,
    });

    if (!completion.ok) {
      return {
        ok: false,
        code: provider.name === "openai" ? "OPENAI_ERROR" : "PROVIDER_ERROR",
        error: completion.error,
      };
    }

    if (completion.toolCalls.length === 0) {
      const text =
        typeof completion.content === "string" && completion.content.length > 0
          ? completion.content
          : "I could not produce a reply.";
      const reply = text.trim();
      await persistTurn(reply);
      return { ok: true, reply };
    }

    // Append the assistant turn that requested tool calls.
    llmMessages.push({
      role: "assistant",
      content: completion.content,
      toolCalls: completion.toolCalls,
    });

    // Execute each tool and append a normalized tool result.
    for (const tc of completion.toolCalls) {
      const result = await executeBookingAgentTool(
        tc.name,
        tc.arguments,
        options.backend,
      );
      llmMessages.push({
        role: "tool",
        toolCallId: tc.id,
        content: result,
      });
    }
  }

  return {
    ok: false,
    code: "TOOL_LIMIT",
    error: "Too many tool rounds; try a narrower question.",
  };
}
