import type { BookingAgentBackend } from "./backend.js";
import { checkChatLimit, type ChatLimitOptions } from "./chatLimit.js";
import type { ConversationStore } from "./conversationStore.js";
import { runIntentMatch, type IntentRouter } from "./intentRouter.js";
import { requestOpenAiChatCompletion, type OpenAiChatMessage } from "./openai.js";
import { buildBookingAgentTools } from "./openaiTools.js";
import { buildBookingAgentSystemPrompt } from "./prompt.js";
import {
  runSecurityChecks,
  type SecurityErrorCode,
  type SecurityOptions,
} from "./security.js";
import { maybeSummarizeHistory, type SummarizeOptions } from "./summarize.js";
import { executeBookingAgentTool } from "./tools.js";

export type BookingAgentUserMessage = {
  role: "user" | "assistant";
  content: string;
};

export type BookingAgentTurnResult =
  | {
      ok: true;
      reply: string;
      /**
       * True when the reply was generated by the chat-limit fallback
       * (the user hit the per-session message cap). The caller can use
       * this to disable the input or surface a banner.
       */
      limited?: boolean;
    }
  | {
      ok: false;
      code:
        | "MISSING_OPENAI_KEY"
        | "OPENAI_ERROR"
        | "OPENAI_EMPTY"
        | "TOOL_LIMIT"
        | SecurityErrorCode;
      error: string;
      hint?: string;
      retryAfterMs?: number;
    };

function sanitizeIncoming(messages: BookingAgentUserMessage[]): BookingAgentUserMessage[] {
  const max = 30;
  const slice = messages.slice(-max);
  return slice.map((m) => ({
    role: m.role,
    content:
      typeof m.content === "string"
        ? m.content.slice(0, 12000)
        : String(m.content ?? "").slice(0, 12000),
  }));
}

export async function runBookingAgentTurn(options: {
  messages: BookingAgentUserMessage[];
  context?: Record<string, unknown>;
  backend: BookingAgentBackend;
  accountTypeId: string;
  openAiApiKey: string | undefined;
  model?: string;
  maxToolSteps?: number;
  /**
   * Optional conversation memory. When both `store` and `sessionId` are
   * provided, prior messages are loaded for the session and the new
   * user/assistant pair is appended after a successful turn.
   */
  store?: ConversationStore;
  sessionId?: string;
  /**
   * Optional pre-LLM router. When the latest user message matches an
   * intent, the SDK skips OpenAI entirely for this turn. Big cost win
   * for high-volume, well-known phrases.
   */
  intentRouter?: IntentRouter;
  /**
   * Optional history compaction. When stored history exceeds
   * `summarize.after`, older messages are replaced with a single summary
   * generated by `summarize.summarizer`. Requires a store with `clear`.
   */
  summarize?: SummarizeOptions;
  /**
   * Scope mode. When `false` (default) the assistant stays inside the
   * marketplace and politely declines anything its tools can't answer.
   * When `true`, the assistant may answer general booking/travel
   * questions and — if `backend.webSearch` is implemented — use the
   * `web_search` tool to look things up online.
   */
  allowOutOfScope?: boolean;
  /** Custom decline text used by strict (in-scope) mode. */
  outOfScopeFallbackText?: string;
  /**
   * Optional security middleware: API-key allowlist, per-message word
   * cap, SQL/prompt-injection heuristics, control-char stripping, and
   * a sliding-window rate limiter. All checks run before any backend
   * or OpenAI call.
   */
  security?: SecurityOptions;
  /** SDK API key supplied by the caller for this turn. */
  sdkApiKey?: string;
  /** Identifier used for rate limiting (e.g. userId, sessionId, IP). */
  rateLimitKey?: string;
  /**
   * Per-session chat-turn limit. When the total user messages
   * (priorHistory + incoming) exceed `chatLimit.maxTurns` (default 4),
   * the SDK returns a support fallback (e.g. WhatsApp link) instead of
   * calling OpenAI.
   */
  chatLimit?: ChatLimitOptions;
}): Promise<BookingAgentTurnResult> {
  if (options.security) {
    const securityResult = await runSecurityChecks({
      messages: options.messages,
      options: options.security,
      providedApiKey: options.sdkApiKey,
      rateLimitKey: options.rateLimitKey ?? options.sessionId,
    });
    if (!securityResult.ok) {
      return {
        ok: false,
        code: securityResult.code,
        error: securityResult.reason,
        retryAfterMs: securityResult.retryAfterMs,
      };
    }
    options = { ...options, messages: securityResult.sanitizedMessages };
  }

  const apiKey = options.openAiApiKey;
  if (!apiKey?.trim()) {
    return {
      ok: false,
      code: "MISSING_OPENAI_KEY",
      error: "OPENAI_API_KEY is not configured on the server.",
      hint: "Set OPENAI_API_KEY (and optionally OPENAI_MODEL, e.g. gpt-4o-mini).",
    };
  }

  const incoming = sanitizeIncoming(options.messages);
  if (incoming.length === 0) {
    return {
      ok: false,
      code: "OPENAI_ERROR",
      error: "No messages provided.",
    };
  }

  const useStore = Boolean(options.store && options.sessionId);
  const sessionId = options.sessionId ?? "";
  const priorHistory: BookingAgentUserMessage[] = useStore
    ? sanitizeIncoming(await options.store!.load(sessionId))
    : [];

  const persistTurn = async (reply: string): Promise<void> => {
    if (!useStore) return;
    try {
      await options.store!.append(sessionId, [
        ...incoming,
        { role: "assistant", content: reply },
      ]);
      if (options.summarize) {
        await maybeSummarizeHistory({
          store: options.store!,
          sessionId,
          options: options.summarize,
        });
      }
    } catch {
      // Storage failures must not break the turn; the reply is still valid.
    }
  };

  const chatLimitHit = checkChatLimit({
    priorHistory,
    incoming,
    options: options.chatLimit,
  });
  if (chatLimitHit) {
    await persistTurn(chatLimitHit.reply);
    return { ok: true, reply: chatLimitHit.reply, limited: true };
  }

  if (options.intentRouter) {
    const lastUser = [...incoming].reverse().find((m) => m.role === "user");
    if (lastUser) {
      try {
        const match = await options.intentRouter(lastUser.content, {
          accountTypeId: options.accountTypeId,
          pageContext: options.context,
        });
        if (match) {
          const reply = await runIntentMatch(match, options.backend);
          await persistTurn(reply);
          return { ok: true, reply };
        }
      } catch {
        // Router errors fall through to the LLM; never fail the turn.
      }
    }
  }

  const model = options.model ?? "gpt-4o-mini";
  const maxSteps = options.maxToolSteps ?? 8;
  const allowOutOfScope = options.allowOutOfScope === true;
  const includeWebSearch =
    allowOutOfScope && typeof options.backend.webSearch === "function";
  const tools = buildBookingAgentTools({ includeWebSearch });

  const system = buildBookingAgentSystemPrompt(
    options.accountTypeId,
    options.context,
    {
      allowOutOfScope,
      outOfScopeFallbackText: options.outOfScopeFallbackText,
    },
  );

  const fullHistory: BookingAgentUserMessage[] = sanitizeIncoming([
    ...priorHistory,
    ...incoming,
  ]);

  let openaiMessages: OpenAiChatMessage[] = [
    { role: "system", content: system },
    ...fullHistory.map((m) => ({
      role: m.role as "user" | "assistant",
      content: m.content,
    })),
  ];

  for (let step = 0; step < maxSteps; step++) {
    const completion = await requestOpenAiChatCompletion({
      apiKey,
      model,
      messages: openaiMessages,
      tools,
    });

    if (!completion.ok) {
      return {
        ok: false,
        code: "OPENAI_ERROR",
        error: completion.error,
      };
    }

    const choice = completion.choice;
    const toolCalls = choice?.tool_calls;

    if (!toolCalls?.length) {
      const text =
        typeof choice?.content === "string"
          ? choice.content
          : "I could not produce a reply.";
      const reply = text.trim();
      await persistTurn(reply);
      return { ok: true, reply };
    }

    openaiMessages = [
      ...openaiMessages,
      {
        role: "assistant",
        content: choice?.content ?? null,
        tool_calls: toolCalls,
      },
    ];

    for (const tc of toolCalls) {
      const name = tc.function?.name;
      const rawArgs = tc.function?.arguments ?? "{}";

      let toolPayload: unknown = rawArgs;
      try {
        toolPayload = JSON.parse(rawArgs) as unknown;
      } catch {
        toolPayload = {};
      }

      const result =
        name && typeof name === "string"
          ? await executeBookingAgentTool(name, toolPayload, options.backend)
          : JSON.stringify({ error: "Invalid tool name" });

      openaiMessages.push({
        role: "tool",
        tool_call_id: tc.id,
        content: result,
      });
    }
  }

  return {
    ok: false,
    code: "TOOL_LIMIT",
    error: "Too many tool rounds; try a narrower question.",
  };
}
